from typing import Any

SETTINGS_META: dict[str, dict[str, Any]] = {
    # === General ===
    "log_level": {
        "category": "General",
        "description": "Niveau de logs : DEBUG, INFO, WARNING, ERROR",
        "help_url": None,
        "type": "string",
        "placeholder": "INFO",
    },
    "project_id": {
        "category": "General",
        "description": "Identifiant unique du projet AgentOS",
        "help_url": None,
        "type": "string",
        "placeholder": "demo-project",
    },
    "environment": {
        "category": "General",
        "description": "Environnement : development, staging, production",
        "help_url": None,
        "type": "string",
        "placeholder": "development",
    },
    # === LLM — OpenRouter ===
    "openrouter_api_key": {
        "category": "LLM — OpenRouter",
        "description": "Clé API OpenRouter pour les modèles LLM (obligatoire)",
        "help_url": "https://openrouter.ai/keys",
        "type": "secret",
        "placeholder": "sk-or-v1-...",
    },
    "openrouter_base_url": {
        "category": "LLM — OpenRouter",
        "description": "URL de base de l'API OpenRouter",
        "help_url": "https://openrouter.ai/docs",
        "type": "string",
        "placeholder": "https://openrouter.ai/api/v1",
    },
    # === LLM — Agent Models ===
    "dev_agent_model": {
        "category": "LLM — Agent Models",
        "description": "Modèle utilisé par l'agent Dev (@DevAgent) pour le code",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "anthropic/claude-sonnet-20241022",
    },
    "content_agent_model": {
        "category": "LLM — Agent Models",
        "description": "Modèle utilisé par l'agent Content pour la génération de contenu",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "openai/gpt-4o-2024-11-20",
    },
    "marketing_agent_model": {
        "category": "LLM — Agent Models",
        "description": "Modèle utilisé par l'agent Marketing",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "anthropic/claude-sonnet-20241022",
    },
    "commerce_agent_model": {
        "category": "LLM — Agent Models",
        "description": "Modèle utilisé par l'agent Commerce",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "openai/gpt-4o-2024-11-20",
    },
    # === LLM — Routing ===
    "model_for_code": {
        "category": "LLM — Routing",
        "description": "Modèle par défaut pour les tâches de type CODE_GEN",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "anthropic/claude-sonnet-20241022",
    },
    "model_for_content": {
        "category": "LLM — Routing",
        "description": "Modèle par défaut pour les tâches de type CONTENT",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "openai/gpt-4o-2024-11-20",
    },
    "model_for_analysis": {
        "category": "LLM — Routing",
        "description": "Modèle par défaut pour les tâches REASONING et DEBUG",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "mistralai/mixtral-8x22b-instruct",
    },
    "model_for_commerce": {
        "category": "LLM — Routing",
        "description": "Modèle par défaut pour les tâches FAST (commerce, recherches rapides)",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "openai/gpt-4o-2024-11-20",
    },
    "model_for_default": {
        "category": "LLM — Routing",
        "description": "Modèle de fallback par défaut pour tous les autres types de tâches",
        "help_url": "https://openrouter.ai/models",
        "type": "string",
        "placeholder": "openai/gpt-4o-2024-11-20",
    },
    # === LLM — Ollama ===
    "ollama_base_url": {
        "category": "LLM — Ollama",
        "description": "URL du serveur Ollama (modèles locaux)",
        "help_url": "https://ollama.ai/download",
        "type": "string",
        "placeholder": "http://ollama:11434",
    },
    "ollama_fallback_model": {
        "category": "LLM — Ollama",
        "description": "Modèle Ollama de fallback quand OpenRouter est indisponible",
        "help_url": "https://ollama.ai/library",
        "type": "string",
        "placeholder": "qwen2.5",
    },
    # === Embedding ===
    "openai_embedding_model": {
        "category": "Embedding",
        "description": "Modèle OpenAI pour les embeddings (vectorisation du texte)",
        "help_url": "https://platform.openai.com/docs/guides/embeddings",
        "type": "string",
        "placeholder": "text-embedding-3-small",
    },
    "openai_embedding_dimensions": {
        "category": "Embedding",
        "description": "Dimensions des vecteurs d'embedding (768 = text-embedding-3-small)",
        "help_url": "https://platform.openai.com/docs/guides/embeddings",
        "type": "int",
        "placeholder": "768",
    },
    "ollama_embedding_model": {
        "category": "Embedding",
        "description": "Modèle d'embedding local via Ollama",
        "help_url": "https://ollama.ai/library/nomic-embed-text",
        "type": "string",
        "placeholder": "nomic-embed-text",
    },
    # === Database ===
    "postgres_host": {
        "category": "Database",
        "description": "Hôte du serveur PostgreSQL",
        "help_url": "https://neon.tech/docs",
        "type": "string",
        "placeholder": "postgres",
    },
    "postgres_port": {
        "category": "Database",
        "description": "Port du serveur PostgreSQL",
        "help_url": None,
        "type": "int",
        "placeholder": "5432",
    },
    "postgres_db": {
        "category": "Database",
        "description": "Nom de la base de données AgentOS",
        "help_url": "https://neon.tech/docs",
        "type": "string",
        "placeholder": "agentos",
    },
    "postgres_user": {
        "category": "Database",
        "description": "Utilisateur PostgreSQL",
        "help_url": None,
        "type": "string",
        "placeholder": "agentos",
    },
    "postgres_password": {
        "category": "Database",
        "description": "Mot de passe PostgreSQL",
        "help_url": None,
        "type": "secret",
        "placeholder": "",
    },
    "database_url": {
        "category": "Database",
        "description": "URL complète PostgreSQL (remplace host/port/db/user/password si définie)",
        "help_url": "https://neon.tech/docs",
        "type": "secret",
        "placeholder": "postgresql+asyncpg://user:pass@host:5432/db",
    },
    # === Redis ===
    "redis_host": {
        "category": "Redis",
        "description": "Hôte du serveur Redis",
        "help_url": "https://redis.io/docs",
        "type": "string",
        "placeholder": "redis",
    },
    "redis_port": {
        "category": "Redis",
        "description": "Port du serveur Redis",
        "help_url": None,
        "type": "int",
        "placeholder": "6379",
    },
    "redis_password": {
        "category": "Redis",
        "description": "Mot de passe Redis",
        "help_url": None,
        "type": "secret",
        "placeholder": "",
    },
    "redis_url": {
        "category": "Redis",
        "description": "URL complète Redis (remplace host/port/password si définie)",
        "help_url": "https://redis.io/docs",
        "type": "secret",
        "placeholder": "redis://:password@host:6379/0",
    },
    # === Cache ===
    "llm_cache_enabled": {
        "category": "Cache",
        "description": "Activer le cache des réponses LLM (réduit les appels et les coûts)",
        "help_url": None,
        "type": "bool",
        "placeholder": "true",
    },
    "llm_cache_ttl": {
        "category": "Cache",
        "description": "Durée de vie du cache LLM en minutes",
        "help_url": None,
        "type": "int",
        "placeholder": "60",
    },
    "session_cache_ttl": {
        "category": "Cache",
        "description": "Durée de vie du cache de session en secondes",
        "help_url": None,
        "type": "int",
        "placeholder": "3600",
    },
    "project_cache_ttl": {
        "category": "Cache",
        "description": "Durée de vie du cache projet en secondes",
        "help_url": None,
        "type": "int",
        "placeholder": "86400",
    },
    # === JWT Authentication ===
    "jwt_secret": {
        "category": "Authentication",
        "description": "Clé secrète JWT pour les tokens d'authentification (CHANGEZ EN PROD)",
        "help_url": "https://jwt.io/introduction",
        "type": "secret",
        "placeholder": "",
    },
    "jwt_algorithm": {
        "category": "Authentication",
        "description": "Algorithme de signature JWT",
        "help_url": "https://pyjwt.readthedocs.io",
        "type": "string",
        "placeholder": "HS256",
    },
    "jwt_expiry_hours": {
        "category": "Authentication",
        "description": "Durée de validité des tokens JWT en heures",
        "help_url": None,
        "type": "int",
        "placeholder": "24",
    },
    # === Rate Limiting ===
    "rate_limit_default": {
        "category": "Rate Limiting",
        "description": "Limite de requêtes par défaut (format: nombre/période)",
        "help_url": "https://slowapi.readthedocs.io",
        "type": "string",
        "placeholder": "100/minute",
    },
    "rate_limit_run": {
        "category": "Rate Limiting",
        "description": "Limite sur l'endpoint /api/v1/run",
        "help_url": None,
        "type": "string",
        "placeholder": "10/minute",
    },
    "rate_limit_plan": {
        "category": "Rate Limiting",
        "description": "Limite sur l'endpoint /api/v1/plan",
        "help_url": None,
        "type": "string",
        "placeholder": "20/minute",
    },
    "rate_limit_verify": {
        "category": "Rate Limiting",
        "description": "Limite sur l'endpoint /api/v1/verify",
        "help_url": None,
        "type": "string",
        "placeholder": "30/minute",
    },
    # === OAuth / NextAuth ===
    "nextauth_secret": {
        "category": "OAuth & SSO",
        "description": "Clé secrète NextAuth pour les sessions SSO (CHANGEZ EN PROD)",
        "help_url": "https://next-auth.js.org",
        "type": "secret",
        "placeholder": "",
    },
    "nextauth_url": {
        "category": "OAuth & SSO",
        "description": "URL publique du frontend Next.js (utilisée par NextAuth)",
        "help_url": "https://next-auth.js.org",
        "type": "string",
        "placeholder": "http://localhost:3000",
    },
    "google_client_id": {
        "category": "OAuth & SSO",
        "description": "Client ID Google OAuth (pour connexion via Google)",
        "help_url": "https://console.cloud.google.com/apis/credentials",
        "type": "string",
        "placeholder": "",
    },
    "google_client_secret": {
        "category": "OAuth & SSO",
        "description": "Client Secret Google OAuth",
        "help_url": "https://console.cloud.google.com/apis/credentials",
        "type": "secret",
        "placeholder": "",
    },
    "github_client_id": {
        "category": "OAuth & SSO",
        "description": "Client ID GitHub OAuth (pour connexion via GitHub)",
        "help_url": "https://github.com/settings/developers",
        "type": "string",
        "placeholder": "",
    },
    "github_client_secret": {
        "category": "OAuth & SSO",
        "description": "Client Secret GitHub OAuth",
        "help_url": "https://github.com/settings/developers",
        "type": "secret",
        "placeholder": "",
    },
    "admin_emails": {
        "category": "OAuth & SSO",
        "description": "Emails administrateurs (séparés par des virgules, pour l'accès admin)",
        "help_url": None,
        "type": "string",
        "placeholder": "admin@example.com",
    },
    # === Stripe ===
    "stripe_api_key": {
        "category": "Stripe",
        "description": "Clé API Stripe (sk_live_... ou sk_test_...)",
        "help_url": "https://dashboard.stripe.com/apikeys",
        "type": "secret",
        "placeholder": "sk_live_...",
    },
    "stripe_webhook_secret": {
        "category": "Stripe",
        "description": "Secret du webhook Stripe (whsec_...)",
        "help_url": "https://dashboard.stripe.com/webhooks",
        "type": "secret",
        "placeholder": "whsec_...",
    },
    "stripe_price_id": {
        "category": "Stripe",
        "description": "ID du prix Stripe pour les abonnements (price_...)",
        "help_url": "https://dashboard.stripe.com/prices",
        "type": "string",
        "placeholder": "price_...",
    },
    # === GitHub ===
    "github_token": {
        "category": "GitHub",
        "description": "Token d'accès GitHub (pour intégration PR, issues, releases)",
        "help_url": "https://github.com/settings/tokens",
        "type": "secret",
        "placeholder": "ghp_...",
    },
    # === Replicate ===
    "replicate_api_token": {
        "category": "Replicate",
        "description": "Token API Replicate (modèles de génération d'images, audio, etc.)",
        "help_url": "https://replicate.com/account/api-tokens",
        "type": "secret",
        "placeholder": "r8_...",
    },
    # === Sandbox ===
    "sandbox_enabled": {
        "category": "Sandbox",
        "description": "Activer l'exécution sandboxée des agents (isole Docker)",
        "help_url": "https://docs.docker.com/compose",
        "type": "bool",
        "placeholder": "true",
    },
    "sandbox_network": {
        "category": "Sandbox",
        "description": "Nom du réseau Docker pour les conteneurs sandbox",
        "help_url": None,
        "type": "string",
        "placeholder": "agentos_net",
    },
    # === HITL ===
    "hitl_mode": {
        "category": "HITL",
        "description": "Mode HITL : webhook_and_cli, webhook_only, cli_only, disabled",
        "help_url": None,
        "type": "string",
        "placeholder": "webhook_and_cli",
    },
    "hitl_timeout": {
        "category": "HITL",
        "description": "Timeout d'attente d'approbation humaine en secondes (0 = infini)",
        "help_url": None,
        "type": "int",
        "placeholder": "0",
    },
    # === API ===
    "api_quota_per_project": {
        "category": "API",
        "description": "Quota maximum de requêtes API par projet",
        "help_url": None,
        "type": "int",
        "placeholder": "1000",
    },
    # === OpenTelemetry ===
    "otlp_endpoint": {
        "category": "Observability",
        "description": "Endpoint OTLP pour l'export des traces (Jaeger)",
        "help_url": "https://www.jaegertracing.io/docs",
        "type": "string",
        "placeholder": "http://jaeger:4318",
    },
    "otlp_enabled": {
        "category": "Observability",
        "description": "Activer l'export des traces OpenTelemetry",
        "help_url": "https://opentelemetry.io/docs",
        "type": "bool",
        "placeholder": "false",
    },
    "service_name": {
        "category": "Observability",
        "description": "Nom du service dans les traces OpenTelemetry",
        "help_url": None,
        "type": "string",
        "placeholder": "agentos",
    },
    # === S3 / MinIO ===
    "s3_endpoint": {
        "category": "Storage",
        "description": "URL du serveur S3/MinIO pour le stockage de fichiers",
        "help_url": "https://min.io/docs",
        "type": "string",
        "placeholder": "http://minio:9000",
    },
    "s3_access_key": {
        "category": "Storage",
        "description": "Clé d'accès S3",
        "help_url": "https://min.io/docs",
        "type": "secret",
        "placeholder": "",
    },
    "s3_secret_key": {
        "category": "Storage",
        "description": "Clé secrète S3",
        "help_url": "https://min.io/docs",
        "type": "secret",
        "placeholder": "",
    },
    "s3_bucket": {
        "category": "Storage",
        "description": "Nom du bucket S3/MinIO",
        "help_url": "https://min.io/docs",
        "type": "string",
        "placeholder": "agentos",
    },
    # === Notifications ===
    "slack_webhook_url": {
        "category": "Notifications",
        "description": "Webhook Slack pour les notifications (Incoming Webhook)",
        "help_url": "https://api.slack.com/messaging/webhooks",
        "type": "secret",
        "placeholder": "https://hooks.slack.com/services/...",
    },
    "discord_webhook_url": {
        "category": "Notifications",
        "description": "Webhook Discord pour les notifications",
        "help_url": "https://discord.com/developers/docs/resources/webhook",
        "type": "secret",
        "placeholder": "https://discord.com/api/webhooks/...",
    },
    "notification_email_from": {
        "category": "Notifications",
        "description": "Adresse email expéditrice pour les notifications",
        "help_url": None,
        "type": "string",
        "placeholder": "agentos@localhost",
    },
    "notification_smtp_host": {
        "category": "Notifications",
        "description": "Hôte SMTP pour l'envoi d'emails",
        "help_url": None,
        "type": "string",
        "placeholder": "mailhog",
    },
    "notification_smtp_port": {
        "category": "Notifications",
        "description": "Port SMTP pour l'envoi d'emails",
        "help_url": None,
        "type": "int",
        "placeholder": "1025",
    },
    # === Scheduler ===
    "scheduler_enabled": {
        "category": "Scheduler",
        "description": "Activer le planificateur de tâches (réflexion nocturne, etc.)",
        "help_url": None,
        "type": "bool",
        "placeholder": "true",
    },
    "scheduler_check_interval": {
        "category": "Scheduler",
        "description": "Intervalle de vérification du planificateur en secondes",
        "help_url": None,
        "type": "int",
        "placeholder": "60",
    },
    "nightly_reflection_cron": {
        "category": "Scheduler",
        "description": "Expression cron pour la réflexion nocturne automatique",
        "help_url": "https://crontab.guru",
        "type": "string",
        "placeholder": "0 2 * * *",
    },
    # === VRAM Manager ===
    "vram_total_gb": {
        "category": "VRAM Manager",
        "description": "VRAM GPU totale disponible en GB (pour le placement des modèles Ollama)",
        "help_url": None,
        "type": "float",
        "placeholder": "12.0",
    },
    "computer_use_enabled": {
        "category": "VRAM Manager",
        "description": "Activer Computer Use Tools (interaction écran, désactivé par défaut)",
        "help_url": None,
        "type": "bool",
        "placeholder": "false",
    },
    "tot_enabled": {
        "category": "Tree of Thoughts",
        "description": "Activer Tree of Thoughts (raisonnement multi-branches)",
        "help_url": "https://github.com/princeton-nlp/tree-of-thought-llm",
        "type": "bool",
        "placeholder": "true",
    },
    "tot_max_branches": {
        "category": "Tree of Thoughts",
        "description": "Nombre maximum de branches parallèles ToT",
        "help_url": None,
        "type": "int",
        "placeholder": "2",
    },
    "tot_max_depth": {
        "category": "Tree of Thoughts",
        "description": "Profondeur maximale de l'arbre ToT",
        "help_url": None,
        "type": "int",
        "placeholder": "3",
    },
    "tot_complexity_threshold": {
        "category": "Tree of Thoughts",
        "description": "Seuil de complexité pour activer ToT (0.0–1.0, au-dessus = activé)",
        "help_url": None,
        "type": "float",
        "placeholder": "0.7",
    },
    # === AutoCorrector ===
    "auto_corrector_enabled": {
        "category": "AutoCorrector",
        "description": "Activer la boucle de correction automatique (stderr → fix → réessai)",
        "help_url": None,
        "type": "bool",
        "placeholder": "true",
    },
    "auto_corrector_max_retries": {
        "category": "AutoCorrector",
        "description": "Nombre maximum de tentatives de correction automatique",
        "help_url": None,
        "type": "int",
        "placeholder": "3",
    },
    # === WasmRunner ===
    "wasm_runner_enabled": {
        "category": "WasmRunner",
        "description": "Activer l'exécution d'outils légers via WebAssembly",
        "help_url": "https://webassembly.org",
        "type": "bool",
        "placeholder": "true",
    },
    "wasm_runner_timeout_ms": {
        "category": "WasmRunner",
        "description": "Timeout maximum pour l'exécution Wasm en millisecondes",
        "help_url": None,
        "type": "int",
        "placeholder": "5",
    },
    # === EphemeralFS ===
    "ephemeral_fs_enabled": {
        "category": "EphemeralFS",
        "description": "Activer les répertoires temporaires par workspace",
        "help_url": None,
        "type": "bool",
        "placeholder": "true",
    },
    # === AgentBus ===
    "agent_bus_enabled": {
        "category": "AgentBus",
        "description": "Activer le bus de messagerie inter-agents (Redis Pub/Sub)",
        "help_url": "https://redis.io/docs",
        "type": "bool",
        "placeholder": "true",
    },
}

SETTINGS_CATEGORIES: dict[str, str] = {
    "General": "Paramètres généraux de l'application",
    "LLM — OpenRouter": "Configuration de l'API OpenRouter pour les modèles LLM cloud",
    "LLM — Agent Models": "Modèles LLM assignés à chaque agent spécialisé",
    "LLM — Routing": "Modèles par défaut pour chaque type de tâche (routage intelligent)",
    "LLM — Ollama": "Configuration des modèles LLM locaux via Ollama",
    "Embedding": "Modèles de vectorisation (RAG, recherche sémantique)",
    "Database": "Configuration de la base de données PostgreSQL (support pgvector)",
    "Redis": "Configuration du cache Redis (sessions, cache LLM, file d'attente)",
    "Cache": "Durées de vie des différents caches",
    "Authentication": "Configuration JWT pour l'authentification API",
    "Rate Limiting": "Limites de requêtes pour les endpoints API",
    "OAuth & SSO": "Configuration OAuth2 pour la connexion Google/GitHub",
    "Stripe": "Configuration des paiements Stripe",
    "GitHub": "Token GitHub pour l'intégration CI/CD et PRs",
    "Replicate": "Token Replicate pour les modèles de génération (images, audio)",
    "Sandbox": "Configuration du bac à sable Docker pour les agents",
    "HITL": "Mode d'approbation humaine (Human In The Loop)",
    "API": "Quotas et limites de l'API",
    "Observability": "Configuration OpenTelemetry et Jaeger pour le tracing",
    "Storage": "Configuration du stockage S3/MinIO",
    "Notifications": "Configuration des notifications Slack, Discord, Email",
    "Scheduler": "Configuration du planificateur de tâches",
    "VRAM Manager": "Gestion de la mémoire GPU pour les modèles Ollama",
    "Tree of Thoughts": "Configuration du raisonnement multi-branches ToT",
    "AutoCorrector": "Configuration de la correction automatique d'erreurs",
    "WasmRunner": "Configuration de l'exécution d'outils WebAssembly",
    "EphemeralFS": "Configuration du système de fichiers temporaire",
    "AgentBus": "Configuration du bus de messagerie inter-agents",
}


def get_settings_schema() -> dict[str, Any]:
    return {
        "fields": SETTINGS_META,
        "categories": SETTINGS_CATEGORIES,
    }
